[package]
name = "Aubrium"
version = "1.0.0"
authors = ["David Lucid <david@pentagon.xyz>", "Jet Jadeja <jet@pentagon.xyz>"]

[dependencies]
Sui = { local = "./lib/sui-framework" }

[addresses]
aubrium = "0x0"
